dotnet/dotnet-operator-sdk

src/KubeOps/Operator/OperatorSettings.cs, src/KubeOps/Operator/Watcher/ResourceWatcher.cs
Http timeout of watcher should be adjustable the same way as kubernetes client library allow it
=> Add setting WatcherHttpTimeout to OperatorSettings

src/KubeOps/Operator/Caching/ResourceCache.cs, tests/KubeOps.Test/Operator/Caching/ResourceCache.Test.cs, tests/KubeOps.Test/TestEntities/TestStatusEntity.cs
This should fix #78 by way of a small tweak to comparison logic in `ResourceCache<TEntity>`
=> Fix Resource Status Comparison

.github/workflows/github-pages.yml, docs/docs/ms_build.md, src/KubeOps/Build/KubeOps.targets, tests/KubeOps.Test/Operator/Caching/ResourceCache.Test.cs
This extends the config possibilities for project files
=> feat: add KubeOpsBasePath to msbuild properties

.github/ISSUE_TEMPLATE/documentation.md, .gitignore, .nuke, .nuke/parameters.json, build.cmd, build.ps1, build.sh, build/Build.cs, src/KubeOps/Operator/Finalizer/IResourceFinalizer.cs
This fixes #193. As stated, the documentation
defines the max length to 63 instead of 254 and
the name should be a domain name.
=> fix(finalizer): use correct max length and name

src/KubeOps/Operator/Builder/OperatorBuilder.cs
=> Remove Self Registration of IServiceProvider

src/KubeOps/Operator/Controller/ManagedResourceController{TEntity}.cs
Currently, if a finalizer throws an exception, it goes completely un-handled and will cause the controller to exit.
Fixes #239
=> Add exception handling and re-queueing to finalizers

docs/docs/templates.md
Update template command given the current one is not valid:
```
$ dotnet new -n Sandbox.Generated.Operator operator
Error: Invalid option(s):
operator
For usage information, run:
dotnet new -h
```
=> docs: Update template command

src/KubeOps/Operator/Builder/OperatorBuilder.cs, src/KubeOps/Operator/Caching/ResourceCache{TEntity}.cs, src/KubeOps/Operator/OperatorSettings.cs, tests/KubeOps.Test/Operator/Caching/ResourceCache.Test.cs
Fixes buehler/dotnet-operator-sdk#364
=> feat: make CompareNETObjects' ComparisonConfig configurable

src/KubeOps/Operator/Webhooks/IMutationWebhook{TEntity}.cs, src/KubeOps/Operator/Webhooks/IValidationWebhook{TEntity}.cs, src/KubeOps/Operator/Webhooks/WebhookEndpointFactory.cs, tests/KubeOps.Test/Operator/Webhook/WebhookEndpointFactory.Test.cs
Fixed invalid endpoint construction with K8s primitive entities, added tests.
Should resolve #425.
=> Fixes Webhook Endpoint Generation

src/KubeOps/Operator/Builder/OperatorBuilder.cs
This PR fixes service resolution after the refactors in https://github.com/buehler/dotnet-operator-sdk/pull/394.
=> Fixes Service Resolution

src/KubeOps.Testing/KubernetesOperatorFactory.cs, src/KubeOps/Operator/Builder/OperatorBuilder.cs
Fixes #441
Signed-off-by: Erin Allison <erin@eallison.us>
=> fix: Kubernetes client registration after refactor

.github/workflows/gh-pages.yml, res/docs_index.md
=> docs: republish gh pages

src/KubeOps.KubernetesClient/IKubernetesClient.cs, src/KubeOps.KubernetesClient/KubernetesClient.cs, src/KubeOps.Testing/MockKubernetesClient.cs
see https://github.com/buehler/dotnet-operator-sdk/discussions/515
=> Adding back API Client

src/KubeOps/Operator/Webhooks/IAdmissionWebhook{TEntity, TResult}.cs
=> Request body deserialization fix in IAdmissionWebhook 

src/KubeOps/Operator/Kubernetes/ResourceWatcher{TEntity}.cs, tests/KubeOps.Test/Operator/Kubernetes/ResourceWatcher{TEntity}.Test.cs
This PR prevents the disposal of the resource watcher during JSON serialization exceptions #477
Fixes #477.
=> Controller is not being called after options.WatcherHttpTimeout has elapsed fix

README.md, examples/Operator/Entities/V1TestEntity.cs, src/KubeOps.Cli/Arguments.cs, src/KubeOps.Cli/Commands/Generator/CrdGenerator.cs, src/KubeOps.Cli/Commands/Generator/RbacGenerator.cs, src/KubeOps.Cli/Commands/Management/Install.cs, src/KubeOps.Cli/Commands/Management/Uninstall.cs, src/KubeOps.Cli/ExitCodes.cs, src/KubeOps.Cli/Options.cs, src/KubeOps.Cli/Output/ResultOutput.cs, src/KubeOps.Cli/Program.cs, src/KubeOps.Cli/Roslyn/AssemblyParser.cs, test/KubeOps.Cli.Test/KubeOps.Cli.Test.csproj, test/KubeOps.Cli.Test/Management/Install.Integration.Test.cs
Adding install / uninstall commands to the CLI.
BREAKING CHANGE: The install / uninstall commands
now search for a project or solution file to parse the
CRDs from a solution or a project.
=> feat(cli): management install/uninstall commands

src/KubeOps.Operator/Queue/TimedEntityQueue.cs, test/KubeOps.Operator.Test/Queue/TimedEntityQueue.Test.cs
=> Timed entity queue should take into account namespace as well as name

src/KubeOps.Operator.Web/KubeOps.Operator.Web.csproj
Upgrade localtunnel to non-preview version that contains license information
=> chore(deps): upgrade localtunnel

src/KubeOps.Abstractions/Kustomize/KustomizationCommonLabels.cs, src/KubeOps.Abstractions/Kustomize/KustomizationCommonLabelsPair.cs, src/KubeOps.Abstractions/Kustomize/KustomizationConfig.cs, src/KubeOps.Cli/Commands/Generator/OperatorGenerator.cs
https://github.com/buehler/dotnet-operator-sdk/issues/854
=> changing the kustomization commonLabels

docs/docs/operator/build-customization.mdx, examples/Operator/Operator.csproj, src/KubeOps.Operator/Build/KubeOps.Operator.targets
=> feat(operator build): allow disable / force / onlyonrelease for operator config
