.github/workflows/dotnet-test.yml, build/Build.cs, src/KubeOps/Operator/KubernetesOperator.cs, src/KubeOps/Testing/KubernetesTestOperator.cs, tests/KubeOps.TestOperator.Test/TestController.Test.cs, tests/KubeOps.TestOperator.Test/TestFinalizer.Test.cs
those tests are running locally :(
=> test: try to fix the failing tests

.gitignore, src/KubeOps/Operator/Entities/Extensions/KubernetesObjectExtensions.cs
This PR adds some utilities that I created in my project to assist in the creation of Kubernetes objects.
=> Add some utility extensions to assist creating Kubernetes objects

src/KubeOps/Operator/Entities/Extensions/EntityToCrdExtensions.cs, tests/KubeOps.Test/Operator/Entities/CrdGeneration.Test.cs, tests/KubeOps.Test/TestEntities/TestSpecEntity.cs
The CRD schema can support arrays of complex entities in the configuration. This PR extends the CRD generation to support this scenario. I added the unit test covering this and it looks good there, and I haven't committed but successfully installed the testEntity with this patched in.
=> Support arrays of complex types in CRD generation

src/KubeOps/Operator/Builder/IOperatorBuilder.cs, src/KubeOps/Operator/Builder/OperatorBuilder.cs, src/KubeOps/Operator/Commands/Generators/CrdGenerator.cs, src/KubeOps/Operator/Commands/Generators/RbacGenerator.cs, src/KubeOps/Operator/Commands/Management/Install.cs, src/KubeOps/Operator/Commands/Management/Uninstall.cs, src/KubeOps/Operator/Services/IResourceTypeService.cs, src/KubeOps/Operator/Services/ResourceTypeService.cs, tests/KubeOps.Test/KubeOps.Test.csproj, tests/KubeOps.Test/Operator/Commands/Generators/CrdGenerator.Test.cs, tests/KubeOps.Test/Operator/Entities/CrdGeneration.Test.cs, tests/KubeOps.Test/Operator/Services/ResourceTypeService.Test.cs
This should close #103. I pulled out assembly listing into a service with an extension to register additional assemblies, with the defaults being the entry and executing assemblies.
As a consequence of not wanting to pass the service instance around too many times, `GenerateCrds` and `GenerateManagerRbac` had their static modifier removed, but that can be worked around if it was needed there.
I don't easily have code built to run tests on this; hoping @Aivanovac can see if this will support his codebase as the requestor of the issue that spawned this.
=> Add extensions for specifying additional assemblies to search for ressources/entities.

docs/docs/commands.md, src/KubeOps/Operator/Builder/OperatorBuilder.cs, src/KubeOps/Operator/Caching/IResourceCache.cs, src/KubeOps/Operator/Caching/ResourceCache.cs, src/KubeOps/Operator/Controller/ResourceControllerBase.cs, src/KubeOps/Operator/OperatorSettings.cs
This closes #58. Note that preload is done on leader election
as well as "each start" of the specific controller.
This could lead to "not catched" resources.
=> feat: add preload cache mechanism via settings

src/KubeOps/Operator/Entities/Annotations/AdditionalPrinterColumnAttribute.cs, src/KubeOps/Operator/Entities/Annotations/DescriptionAttribute.cs, src/KubeOps/Operator/Entities/Annotations/EmbeddedResource.cs, src/KubeOps/Operator/Entities/Annotations/EmbeddedResourceAttribute.cs, src/KubeOps/Operator/Entities/Annotations/ExternalDocsAttribute.cs, src/KubeOps/Operator/Entities/Annotations/GenericAdditionalPrinterColumnAttribute.cs, src/KubeOps/Operator/Entities/Annotations/ItemsAttribute.cs, src/KubeOps/Operator/Entities/Annotations/LengthAttribute.cs, src/KubeOps/Operator/Entities/Annotations/MultipleOfAttribute.cs, src/KubeOps/Operator/Entities/Annotations/PatternAttribute.cs, src/KubeOps/Operator/Entities/Annotations/PreserveUnknownFieldsAttribute.cs, src/KubeOps/Operator/Entities/Annotations/RangeMaximum.cs, src/KubeOps/Operator/Entities/Annotations/RangeMinimum.cs, src/KubeOps/Operator/Entities/Annotations/RequiredAttribute.cs, src/KubeOps/Operator/Entities/CustomKubernetesEntity.cs, src/KubeOps/Operator/Entities/CustomKubernetesEntity{TSpec,TStatus}.cs, src/KubeOps/Operator/Entities/CustomKubernetesEntity{TSpec}.cs, src/KubeOps/Operator/Entities/Extensions/EntityToCrdExtensions.cs, tests/KubeOps.Test/Operator/Entities/CrdGeneration.Test.cs, tests/KubeOps.Test/TestEntities/TestSpecEntity.cs, tests/KubeOps.TestOperator/Entities/V2TestEntity.cs, tests/KubeOps.TestOperator/test.yaml
This closes #60. An additional `[AdditionalPrinterColumn]`
adds the possibility to add a specific property as an
additional printer column. The additional
`[GenericAdditionalPrinterColumn]` adds the possibility
to add any spec path to the additional printer columns.
Additionally, documentation for the various
property and class attributes for entities was
added.
Signed-off-by: Christoph Bühler <christoph@smartive.ch>
=> feat(crd generation): Add additional printer columns.

docs/docs/events.md, docs/docs/toc.yml, docs/docs/utilities.md, src/KubeOps/KubeOps.csproj, src/KubeOps/Operator/Builder/OperatorBuilder.cs, src/KubeOps/Operator/Events/EventManager.cs, src/KubeOps/Operator/Events/EventType.cs, src/KubeOps/Operator/Events/IEventManager.cs, tests/KubeOps.Test/Operator/Events/EventManager.Test.cs, tests/KubeOps.Test/Operator/Leadership/LeaderElector.Test.cs, tests/KubeOps.TestOperator/Controller/TestController.cs
This closes #5.
The provided IEventManager helps with publishing
singleton events (fire and forget) and event series.
The event-name is deterministic, so if the same event
is published multiple times, an event series is created
(when used with Publish(string,string...)).
/cc @ocdi
=> feat(events): Add event support for resources and controllers.

src/KubeOps/Operator/Entities/Extensions/EntityToCrdExtensions.cs, tests/KubeOps.Test/Operator/Entities/CrdGeneration.Test.cs, tests/KubeOps.Test/TestEntities/TestSpecEntity.cs
This fixes #152 by expanding the collection types the CRD code generator can correctly declare as `array` in the JSON Schema.
=> fix: Expand code generator support for enumerable and collection types

src/KubeOps/Operator/Entities/Extensions/EntityToCrdExtensions.cs, tests/KubeOps.Test/Operator/Entities/CrdGeneration.Test.cs
This fixes #156 by setting the `type` of embedded resource properties to `object` in the generated schema.
=> fix: CRD schema type for x-kubernetes-embedded-resource should be object

src/KubeOps/Operator/Entities/Extensions/EntityToCrdExtensions.cs, src/KubeOps/Operator/Util/StringExtensions.cs, tests/KubeOps.Test/Operator/Entities/CrdGeneration.Test.cs, tests/KubeOps.Test/TestEntities/TestSpecEntity.cs
This fixes #158 by setting the schema property name to the `JsonPropertyAttribute.PropertyName` value if set on the `PropertyInfo` instance before applying camel-casing.
=> fix: CRD schema generator does not take JsonProperty.PropertyName value into consideration

src/KubeOps/Operator/Entities/Extensions/EntityToCrdExtensions.cs, tests/KubeOps.Test/Operator/Entities/CrdGeneration.Test.cs, tests/KubeOps.Test/TestEntities/TestSpecEntity.cs
Update the CRD generator to treat all `IKubernetesObject` types from the k8s client assembly as embedded resources.
This allows properties to be declared that are arrays of `IKubernetesObject` or its derived types.
```c#
public IList<V1Pod> Pods { get; set; } = Array.Empty<V1Pod>();
```
It also means that properties do not have to have the `EmbeddedResourceAttribute` applied to result in the correct schema being generated.
```c#
public IKubernetesObject PolymorphicKubernetesObject { get; set; } = new V1Pod();
```
=> feat(crd generation): Treat IKubernetesObject types as x-kubernetes-embedded-resource

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, docs/docs/templates.md, docs/docs/toc.yml
This provides documentation for the various templates
(operator and operator empty) in the kubeops.templates
package.
Additionally, github issue templates are provided to
ease up creation of issues.
This closes #171.
=> docs(templates): provide documentation for kubeops templates

src/KubeOps/Operator/Controller/ManagedResourceController{TEntity}.cs, src/KubeOps/Operator/Controller/Results/RequeueEventResult.cs, src/KubeOps/Operator/Controller/Results/ResourceControllerResult.cs, src/KubeOps/Operator/OperatorSettings.cs
@buehler What do you think of this as an option to resolve #77?
Adding an extra parameter to `ResourceControllerResult.RequeueEvent()` lets the change be backwards compatible, and adding a flag on the `OperatorSettings` allows for the behavior @sabbadino requested, to have the library default to requeueing with the original event type.
=> Allow forcing of event method for requeued resource

src/KubeOps/Operator/Builder/OperatorBuilder.cs, src/KubeOps/Operator/HostExtensions.cs, src/KubeOps/Operator/OperatorSettings.cs, src/KubeOps/Operator/Serialization/EntitySerializer.cs, src/KubeOps/Operator/Webhooks/IAdmissionWebhook{TEntity, TResult}.cs
The library really shouldn't rely upon or modify the default JsonSerializerSettings since other libraries could conflict, user code could muck with it, etc.
This fixes #242
=> Remove modification/usage of default JsonSerializerSettings

src/KubeOps/Operator/Builder/OperatorBuilder.cs, src/KubeOps/Operator/Webhooks/MutatingWebhookBuilder.cs, src/KubeOps/Operator/Webhooks/ValidatingWebhookBuilder.cs
This fixes #257. With the refactoring of #252, mutators
and validators became registered within a scope.
The generation of the config must create a scope.
=> fix: Use Scoping for webhook builders.

docs/docs/webhooks.md, src/KubeOps/KubeOps.csproj, src/KubeOps/Operator/Builder/AssemblyScanner.cs, src/KubeOps/Operator/Builder/ComponentRegistrar.cs, src/KubeOps/Operator/Builder/IOperatorBuilder.cs, src/KubeOps/Operator/Builder/OperatorBuilder.cs, src/KubeOps/Operator/Commands/Management/Webhooks/Register.cs, src/KubeOps/Operator/Controller/ManagedResourceController{TEntity}.cs, src/KubeOps/Operator/OperatorBuilderExtensions.cs, src/KubeOps/Operator/Rbac/RbacBuilder.cs, src/KubeOps/Operator/Webhooks/IAdmissionWebhook{TEntity, TResult}.cs, src/KubeOps/Operator/Webhooks/IMutationWebhook{TEntity}.cs, src/KubeOps/Operator/Webhooks/IValidationWebhook{TEntity}.cs, src/KubeOps/Operator/Webhooks/MutatingWebhookBuilder.cs, src/KubeOps/Operator/Webhooks/MutationResult.cs, src/KubeOps/Operator/Webhooks/WebhookLocalTunnel.cs, tests/KubeOps.TestOperator/Program.cs, tests/KubeOps.TestOperator/Startup.cs
This closes #253. When developing webhooks, one needed to
start the operator locally, then use some technology like "localtunnel"
or "ngrok" to have a tunnel (with HTTPS) to the local running operator
and then register that given randomized url to Kubernetes to
actually call the migrator/validator.
This pull request uses localtunnel as a libary by adding `AddWebhookLocaltunnel`
to the operator builder. With this, the operator creates a localtunnel
during startup and registers itself within Kubernetes with the returned url.
Note: this should never be used in production.
=> feat: Use Localtunnel to improve developer experience

src/KubeOps/Operator/Builder/OperatorBuilder.cs, src/KubeOps/Operator/Leadership/DisabledLeaderElection.cs, src/KubeOps/Operator/Leadership/LeaderElector.cs, src/KubeOps/Operator/OperatorSettings.cs, src/KubeOps/Operator/Rbac/RbacBuilder.cs, tests/KubeOps.TestOperator/Startup.cs
This also fixes #254. When no
leader election is used, the operator
is always considered "leader". Furthermore, if leader election
is configured, the RBAC generator
includes V1Lease and V1Deployment rules.
This also closes #255.
=> feat: Make LeaderElection configurable.

src/KubeOps/Build/KubeOps.targets
Resolves #272.
This adds a check for the assembly before/after timestamp and if the timestamps are different then the CRDs, etc. will be generated; if not, it won't regenerate because nothing has changed.
I didn't bother adding a configuration for "always rebuild" because you can force a rebuild by doing a clean. It doesn't seem like you'd want to rebuild every time, right? And if you did, you'd rebuild the whole assembly, which would change the timestamp and trigger a regeneration anyway.
=> Fix #272: Only regenerate if the assembly changed.

.editorconfig, src/KubeOps/Operator/Commands/Generators/OperatorGenerator.cs
Resolves #274 by adding the same labels to `.spec.selector.matchLabels` as are in `.spec.template.metadata.labels`.
As part of this I also added an `.editorconfig` (same one we use for Autofac, but it has some reasonable defaults and matches the current editor style/settings from what I can tell) to ensure contributions will match the repo indent styles, etc. I can nuke that if it's not interesting.
=> Fix #274: Add `selector` to generated deployment

docs/docs/controller.md, docs/docs/features.md, src/KubeOps/Operator/Caching/CacheComparisonResult.cs, src/KubeOps/Operator/Caching/ResourceCache{TEntity}.cs, src/KubeOps/Operator/Controller/IResourceController{TEntity}.cs, src/KubeOps/Operator/Controller/ManagedResourceController{TEntity}.cs, src/KubeOps/Operator/DevOps/ResourceControllerMetrics{TEntity}.cs, src/KubeOps/Operator/Kubernetes/ResourceEventType.cs, tests/KubeOps.Test/Operator/Caching/ResourceCache.Test.cs, tests/KubeOps.TestOperator.Test/TestController.Test.cs, tests/KubeOps.TestOperator/Controller/TestController.cs, tests/KubeOps.TestOperator/TestManager/IManager.cs, tests/KubeOps.TestOperator/TestManager/TestManager.cs
This closes #292.
BREAKING CHANGE: This removes the separat methods
for "created", "updated", and "not modified" events.
Those events are combined into one event "reconcile".
According to https://en.wikipedia.org/wiki/Control_loop,
this is considered good practice. To migrate, remove
all references to the mentioned events and replace
them with one call to "reconcileasync".
=> feat: Combine resource events created,updated,notmodified.

src/KubeOps/Operator/Webhooks/AdmissionResult.cs
This fixes #288. `StatusCode`, `StatusMessage` and `Valid`
are now public members of the `AdmissionResult` instead of internal ones.
This may help in unit/integration testing webhooks.
=> feat(Webhooks): Make StatusCode/StatusMessage public.

src/KubeOps/Operator/Controller/ManagedResourceController{TEntity}.cs, src/KubeOps/Operator/Errors/BackoffStrategies.cs, src/KubeOps/Operator/Kubernetes/ResourceWatcher{TEntity}.cs, src/KubeOps/Operator/OperatorSettings.cs
This closes #276. It adds a configurable amount
of error retries to the operator settings. Furthermore,
the backoff strategy may be configured as well. It defaults
to the exponential backoff used until now.
=> feat(Error Retry): Allow configurable backoff and count.

src/KubeOps/KubeOps.csproj, src/KubeOps/Operator/Entities/Extensions/EntityToCrdExtensions.cs, tests/KubeOps.Test/Operator/Entities/CrdGeneration.Test.cs
map[keyType]valueType is a valid resulting type, it is not a valid OpenAPI v3 type
fixes #377
=> use additionalProperties to create maps with defined key types

src/KubeOps/Operator/Entities/CrdBuilder.cs, tests/KubeOps.Test/Operator/Generators/CrdGenerator.Test.cs
This pr filters out non-CRD's (K8s resources such as Pods and Deployments). This resolves #371 (which we are running into too) where if a controller watches a K8s resource, that resource is included in CRD's on generation (which makes K8s unhappy).
=> Filter K8s Resources from CRD Generation

src/KubeOps/Operator/Controller/ResourceControllerManager.cs, src/KubeOps/Operator/OperatorSettings.cs
This pr adds the ability to opt-out of the default "only listen to resource changes while leader" functionality.
This is to handle cases where leadership is handled at a higher level or if instances still need to watch for resource events with not leading, for example,
- Multiple replicas are deployed to a cluster. One instance is elected as a leader.
- Each operator is configured to respond to webhook events (mutation or admission) based on the state of the cluster (since K8s does not have a built-in way to redirect traffic to only some pods).
- For performance, each instance builds an internal cluster state that webhook events use for reference.
This should be a non-breaking change, since the default behavior is preserved.
=> Flag to Configure Non-Leader Handling

src/KubeOps/Operator/Webhooks/AdmissionResponse.cs, src/KubeOps/Operator/Webhooks/IMutationWebhook{TEntity}.cs
Same as #446, but for next. This pr cherry-picks the commit from #446 and fixes the `AdmissionResponse` model. This actually throws a warning in the K8s api controller (but there was no other impact).
=> Set PatchType Correctly (Next)

src/KubeOps/Operator/Finalizer/FinalizerManager{TEntity}.cs
This pr handles an exception during logging that could be thrown when finalizers are null and not empty. This appears to occur when working with pods.
=> Fixes Exception on Null Finalizers

src/KubeOps/Operator/Webhooks/IMutationWebhook{TEntity}.cs
I was looking though k8s api logs and I noticed this property is missing. This pr sets the PatchType when Patch is set.
=> Set PatchType Correctly

src/KubeOps.KubernetesClient/KubernetesClient.cs
While using the latest version of KubeOps,KubernetesClient, I've noticed that retrieval of kubernetes resources (ConfigMaps and a Deployment) was not working when passing a namespace.  
After further investigation, I've noticed that the underlying `GenericClient<>.ReadNamespacedAsync()` function had swapped parameters which was causing retrieval of resources to fail.
=> fix: IKubernetesClient.Get<> not retrieving namespaced resources due to parameter swap

src/KubeOps/Operator/Kubernetes/ResourceWatcher{TEntity}.cs
Removed disposal of `_reconnectHandler` in `ResourceWatcher` which causes `ObjectDisposedException` after [leader reelections](https://github.com/buehler/dotnet-operator-sdk/blob/a2290ff9edc41bbbb3a7b47a13a00c99e469f8f9/src/KubeOps/Operator/Controller/ResourceControllerManager.cs#L45) and the watcher stops observing the resource. #522
The situation happens after a consecutive call to `StartAsync` after `StopAsync`:
```C#
await _watcher.StartAsync();
await _watcher.StopAsync();
await _watcher.StartAsync();
```
The `_reconnectHandler ` should be disposed only in the if statement of the Disposing method:
```C#
private void Disposing(bool fromStop)
{
if (!fromStop)
{
_watchEvents.Dispose();
_reconnectHandler.Dispose();
}
// _reconnectHandler.Dispose(); // this causes an error later on
//...
} …
```
=> ResourceWatcher reconnection fixes

src/KubeOps/Operator/Builder/OperatorBuilder.cs, src/KubeOps/Operator/DevOps/IResourceWatcherMetrics{TEntity}.cs, src/KubeOps/Operator/DevOps/ResourceWatcherMetrics{TEntity}.cs, src/KubeOps/Operator/Kubernetes/ResourceWatcher{TEntity}.cs, tests/KubeOps.Test/Operator/Kubernetes/ResourceWatcher{TEntity}.Test.cs
This PR enables testability for the `ResourceWatcher<TEntity>` class see also #523 by extracting a new interface `IResourceWatcherMetrics<TEntity>`.
=> Extracted IResourceWatcherMetrics interface for mocking in unit tests

src/KubeOps/Operator/Kubernetes/ResourceWatcher{TEntity}.cs, tests/KubeOps.Test/KubeOps.Test.csproj, tests/KubeOps.Test/Operator/Kubernetes/ResourceWatcher{TEntity}.Test.cs
I apologize that I'm providing the tests in 2 phases for the `ResourceWatcher`, but it was "nontrivial" to write them due to `k8s.Watcher` etc.
Thank you! 
#482 #522 #523 #526
=> Improved ResourceWatcher restart unit test

src/KubeOps/Operator/Webhooks/AdmissionResponse.cs
This PR changes back the AdmissionResponse.PatchType to an optional value #536 since validation web hooks cannot contain a PatchType.
Fixes #536
=> fixed AdmissionResponse.PatchType to an optional value

src/KubeOps/Operator/Commands/Management/Webhooks/Install.cs, src/KubeOps/Operator/Webhooks/IConfigurableMutationWebhook.cs, src/KubeOps/Operator/Webhooks/IConfigurableValidationWebhook.cs, src/KubeOps/Operator/Webhooks/MutatingWebhookBuilder.cs, src/KubeOps/Operator/Webhooks/ValidatingWebhookBuilder.cs
=> Adds the ability to replace webhooks on startup and configure the webhooks when creating (#525 and #532)

src/KubeOps/README.md
This PR fixes a "Page not found exception" for the CLI commands in the "Update Entrypoint" section of KubeOps readme.md.
[CLI Commands](https://github.com/buehler/dotnet-operator-sdk/blob/master/src/KubeOps/commands.md) link.
=> CLI commands link fix

src/KubeOps/Operator/Controller/ManagedResourceController{TEntity}.cs
Give a little better message for errors returned by k8s (at least for code 422).
K8S api will return a V1Status when the API rejects a call. This can be output to the users in the log
=> Parse out V1Status for code 422 on Reconcile loop of ManagedController

src/KubeOps.Testing/KubernetesOperatorFactory.cs, src/KubeOps/Operator/Commands/CommandHelpers/CertificateGenerator.cs, src/KubeOps/Operator/Commands/Generators/DockerGenerator.cs, src/KubeOps/Operator/Commands/Generators/OperatorGenerator.cs, src/KubeOps/Operator/Commands/Management/Webhooks/Install.cs, src/KubeOps/Operator/Controller/IManagedResourceController.cs, tests/KubeOps.TestOperator.Test/TestController.Test.cs
This PR makes sure that the init pod will use pre-downloaded binaries, so that the operator can be deployed in offline scenarios. Also it no longer makes the assumption that binaries like `sh` and `chmod` exist in the docker image (a lot of hardened/ minimal images don't have shell on them). 
Other changes:
- modified `server.pem` and `server-key.pem` to `ca.pem` and `ca-key.pem` - AFAICT, these are the file names generated by cfssljson ; yes I know it's confusing but these are different than the input ones.
- passed additional argument "-r" to the init pod - we don't want it failing on subsequent deployments/ if a webhook already exists. 
Fixes #567.
=> fix: use pre-downloaded binaries for cfssl

src/KubeOps/Operator/Commands/Management/Webhooks/Install.cs
Fixes mutating webhook configuration not being updated by the command `webhook install -r` when the object already exists.
=> fix: update mutating webhook configuration

src/KubeOps/Operator/Commands/RunOperator.cs
Because System is a global import, this Version class actually refers to [Version Class (System) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.version?view=net-7.0).
=> fix version command

src/KubeOps/Operator/Commands/RunOperator.cs, src/KubeOps/Operator/HostExtensions.cs
So now it looks like this:
```
(base) PS E:\Git\github.com\stevefan1999-personal\dotnet-operator-sdk\src> dotnet run --project KubeOps.Play --framework net7.0 -- generator abcd
Building...
Specify --help for a list of available options and commands.
Unrecognized command or argument 'abcd'
Usage: KubeOps.Play generator [command] [options]
Options:
-f|--format <FORMAT>    Determines the output format for the generator.
Allowed values are: Yaml, Json.
-o|--out <OUTPUT_PATH>  The "root" path for the generator to put files in - if empty, prints to console.
-?|-h|--help            Show help information.
Commands:
crd                     Generates the needed CRD for kubernetes.
docker                  Generates the docker file for building.
installer               Generates kustomization yaml …
```
=> Generate good help text instead of stack trace on unrecognized command

src/KubeOps/Operator/Commands/CommandHelpers/CertificateGenerator.cs
With #568 these executables are no longer downloaded on demand, but rather predownloaded to the system.
When running dotnet build locally, it attempts to run `./cfssl` and `./cfssljson` from `/operator` or `$CFSSL_EXECUTABLES_PATH`. However, it deletes them after it's done.
Next time you try build again after cleaning the local dir it'll fail.
=> fix: don't delete cfssl and cfssljson

src/KubeOps/KubeOps.csproj, src/KubeOps/Operator/Webhooks/KubernetesJsonDiffer.cs, tests/KubeOps.Test/Operator/Webhook/KubernetesJsonDiffer.Test.cs
The main motivation behind this change is to remove the deprecated transitive dependency `NetCoreApp 1.1` from `JsonDiffPatch`. This is causing validation issues in built images that are run through Aqua Trivy vulnerability scanner. 
A nice side-effect is that the diff should be much faster as it uses `System.Text.Json` instead of `Newtonsoft`.
Functionally, there should be no impact as both libraries adhere to `RFC 6902`.
@buehler
=> feat: use updated/faster JsonDiffPatch library 

src/KubeOps.Cli/Arguments.cs, src/KubeOps.Cli/Commands/Generator/CertificateGenerator.cs, src/KubeOps.Cli/Commands/Generator/Generator.cs, src/KubeOps.Cli/KubeOps.Cli.csproj, src/KubeOps.Cli/Output/OutputFormat.cs, src/KubeOps.Cli/Output/ResultOutput.cs, test/KubeOps.Cli.Test/Generator/CertificateGenerator.Test.cs
BREAKING CHANGE: This allows the operator
to create a valid selfsigned CA and server
certificate ad-hoc in the cluster when using
webhooks. Instead of generating the certificates
locally and using them as config-map in kustomize,
the operator can run the cli to generate the service
certificate.
=> feat(cli): add certificate generator command

src/KubeOps/Operator/Caching/IResourceCache.cs, src/KubeOps/Operator/Caching/ResourceCache{TEntity}.cs, src/KubeOps/Operator/Controller/EventQueue.cs, src/KubeOps/Operator/Kubernetes/ResourceWatcher{TEntity}.cs, tests/KubeOps.Test/Operator/Kubernetes/ResourceWatcher{TEntity}.Test.cs
Watcher and Local events are now merged to produce a sequence containing all captured events instead of just the sequence that was last produced. Events will still be switch but only at group level, grouping by resource Uid and sub-grouping by event type, therefore Keeping alway last event for each type of each resources, preventing events accumulation.
Fixes #585 #579
=> [Feat] Merge Watch & Local events. Switch by uid & type grouping.

src/KubeOps.KubernetesClient/LabelSelectors/Extensions.cs, test/KubeOps.KubernetesClient.Test/LabelSelector.Test.cs
Current inplementation of ```ToExpression(this IEnumerable<LabelSelector> selectors)``` extension method returns wrong result
```
EqualsSelector { Label = app, Values = System.String[] },NotEqualsSelector { Label = srv, Values = System.String[] }
```
it just serialize record LabelSelector to ```EqualsSelector { Label = app, Values = System.String[] }``` or to ```NotEqualsSelector { Label = srv, Values = System.String[] }``` instead of calling implicit to string convertor.
The proposed pull request corrects this unpleasant behavior. Tests are attached.
=> Fixed ToExpression(this IEnumerable<LabelSelector> selectors) extension method

src/KubeOps.Operator.Web/Webhooks/Admission/Mutation/JsonDiffer.cs
Concurrent execution of JsonDiffer() on multiple threads causes ArgumentOutOfRangeException during Dispose().
Create new instance of JsonPatchDeltaFormatter for every call.
Please refer to this issue: https://github.com/buehler/dotnet-operator-sdk/issues/682
=> fix: make JsonDiffer thread safe

examples/Operator/Entities/V1TestEntity.cs, src/KubeOps.Transpiler/Crds.cs, test/KubeOps.Transpiler.Test/Crds.Mlc.Test.cs
Howdy
Some context for this reasonably large refactor:
- There appears to be mostly consistent issues with the CRD transpiler with 8.0.0-pre.40 as communicated #687 
- This issue was not limited to int/int? alone after further investigation, but instead a whole slew of types (DateTime,bool,bool?,etc)
- long story short, type equality checks were the culprit (and I have no idea why). My best guess is that something is off with my machine.
- While switching out conditions, I noticed opportunities to simplify
I packaged up the code and published it to a local nuget server before installing it in a project. I was able to build the CRD for this entity without any issues with these changes (functionally the kubebuilder book CronJob example):
```csharp
[k8s.Models.KubernetesEntity(Group = …
```
=> fix: Transpiler inconsistencies for CRDs

src/KubeOps.Operator/Watcher/ResourceWatcher{TEntity}.cs, test/KubeOps.Operator.Test/Controller/CancelEntityRequeue.Integration.Test.cs, test/KubeOps.Operator.Test/Controller/EntityController.Integration.Test.cs, test/KubeOps.Operator.Test/Controller/EntityRequeue.Integration.Test.cs
With reference to https://github.com/buehler/dotnet-operator-sdk/issues/707
This fixes the behaviour of requeues
=> Fix queues not polling when status updated

src/KubeOps.Operator/Watcher/ResourceWatcher{TEntity}.cs
Fixes #724 
Restart the watch loop when we receive HTTP 410 Gone, which seems to mirror what other k8s frameworks are doing (see: java).
I tested this for a few hours on my clusters and it _seems_ to fix the issue, but will continue monitoring over the next few days.
=> Watching resource with old version should restart

src/KubeOps.KubernetesClient/KubernetesClient.cs, src/KubeOps.Operator/LeaderElection/LeaderElectionBackgroundService.cs, src/KubeOps.Operator/Queue/EntityRequeueBackgroundService.cs, src/KubeOps.Operator/Watcher/LeaderAwareResourceWatcher{TEntity}.cs, src/KubeOps.Operator/Watcher/ResourceWatcher{TEntity}.cs, test/KubeOps.Operator.Test/HostedServices/LeaderResourceWatcher.Integration.Test.cs, test/KubeOps.Operator.Test/HostedServices/ResourceWatcher.Integration.Test.cs
This PR is ensuring that the host does not stop with an exception. Those exceptions were occuring because the `CancellationTokenSource` inside the hosted services was already disposed when `StopAsync` got called.
The reason for this is that the host invokes `DisposeAsync` **before** `StopAsync`.
=> fix: don't access disposed resources

src/KubeOps.Cli/README.md
Quick fix for #742.
Related to #756. That PR has added documentation for development webhooks.
=> fix(docs): Remove old CLI commands

src/KubeOps.Operator/LeaderElection/LeaderElectionBackgroundService.cs, src/KubeOps.Operator/Watcher/LeaderAwareResourceWatcher{TEntity}.cs, src/KubeOps.Operator/Watcher/ResourceWatcher{TEntity}.cs, test/KubeOps.Operator.Test/KubeOps.Operator.Test.csproj, test/KubeOps.Operator.Test/LeaderElector/LeaderElectionBackgroundService.Test.cs, test/KubeOps.Operator.Test/Watcher/ResourceWatcher{TEntity}.Test.cs
Fixes #677.
This pull request fixes the following behavioral issues noted when testing a leader-aware operator with transient network issues:
- In `LeaderElectionBackgroundService`, if `elector.RunUntilLeadershipLostAsync()` throws, the exception is not observed in the library and no further attempts to become the leader occur. The library now logs any unexpected exceptions and tries to become the leader again.
-  A leader could not stop and then subsequently start being a leader once more due to cancellation token sources not being recreated. The library now disposes and recreates the cancellation token sources as required.
- `LeaderAwareResourceWatcher<TEntity>.StoppedLeading` would erroneously pass a cancelled cancellation token to `ResourceWatcher<TEntity>`. The library now passes the …
=> fix: Leader election failure to restart

src/KubeOps.Operator/LeaderElection/LeaderElectionBackgroundService.cs, test/KubeOps.Operator.Test/LeaderElector/LeaderElectionBackgroundService.Test.cs
Fixes #785.
Introduce a retry delay before attempting to reacquire leadership, fixing the log noise generated from the API server being unavailable.
@buehler
=> fix(leader-election): introduce delay before attempting to reacquire leadership

src/KubeOps.Cli/Transpilation/AssemblyLoader.cs
- Limit the amount of types to process, ignore interface, abstract and generic classes
- This change enables to write a base webhook for multiple types instead of duplicating the webhook logic
=> Limit the amount of types to process

src/KubeOps.Generator/KubeOps.Generator.csproj, src/KubeOps.Generator/README.md
Fixes: #698 
This will cause `dotnet add package` to add this to the PackageReference automatically:
```
<PrivateAssets>all</PrivateAssets>
<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
```
It will also show on nuget.org:
This flag is used by other source generators to fix the problem in #698
This flag is documented for .nuspec files but also works with `dotnet pack` in the csproj
=> Set KubeOps.Generator as a DevelopmentDependency

examples/ConversionWebhookOperator/ConversionWebhookOperator.csproj, examples/Operator/Operator.csproj, examples/WebhookOperator/WebhookOperator.csproj, src/KubeOps.Abstractions/KubeOps.Abstractions.csproj, src/KubeOps.Cli/KubeOps.Cli.csproj, src/KubeOps.KubernetesClient/KubeOps.KubernetesClient.csproj, src/KubeOps.Operator.Web/Certificates/CertificateExtensions.cs, src/KubeOps.Operator.Web/KubeOps.Operator.Web.csproj, src/KubeOps.Operator/KubeOps.Operator.csproj, src/KubeOps.Transpiler/KubeOps.Transpiler.csproj, test/Directory.Build.props, test/KubeOps.Operator.Web.Test/Builder/OperatorBuilderExtensions.Test.cs, test/KubeOps.Operator.Web.Test/IntegrationTestCollection.cs
This will allow us to also support .net 9 that was release in Nov 2024. namely, the CLI will now function in .net 9 and not need dual SDKs
cc: @buehler
=> updating to dotnet 9

src/KubeOps.Abstractions/Entities/Attributes/PreserveUnknownFieldsAttribute.cs, src/KubeOps.Transpiler/Crds.cs, test/KubeOps.Transpiler.Test/Crds.Mlc.Test.cs
PreserveUnknownFieldsAttribute can currently only be applied to properties. If within my CRD I have a List<T> and I set the attribute, it will render in the CRD at the items level, not within the object itself.
```csharp
[KubernetesEntity(Group = "test.io", Kind = "Test", ApiVersion = "v1")]
public partial class TestCrd : CustomKubernetesEntity<TestSpec> { }
public class TestSpec
{
[PreserveUnknownFields]
public List<Item> Items { get; set; } = default!;
}
public class Item
{
public string Name { get; set; } = default!;
}
```
Generates
```yaml
- name: v1
schema:
openAPIV3Schema:
properties:
spec:
properties:
items:
items:
properties:
name:
type: string
type: object
type: array
x-kubernetes-preserve-unknown-fields: true
type: object
type: object
```
x-kubernetes-preserve-unknown-fields: …
=> fix: x-kubernetes-preserve-unknown-fields incorrectly applied on List<T>

src/KubeOps.Abstractions/Kustomize/KustomizationCommonLabels.cs, src/KubeOps.Abstractions/Kustomize/KustomizationCommonLabelsPair.cs
This pull request refactors the handling of common labels in the `KustomizationCommonLabels` class and its associated `KustomizationCommonLabelsPair` class to simplify the data structure and improve usability. The most important changes include replacing the `KustomizationCommonLabelsPair` class with a direct inheritance from `Dictionary<string, string>` and updating the `KustomizationCommonLabels` class to reflect this change.
* [`src/KubeOps.Abstractions/Kustomize/KustomizationCommonLabelsPair.cs`](diffhunk://#diff-500791e44853948e64cc50e1fbd37cb5ba56cef839636e30ab119a7ea54ba332L3-R3): Simplified the `KustomizationCommonLabelsPair` class by making it directly inherit from `Dictionary<string, string>`, removing its properties and methods.
* …
=> Removing the nested Pair

src/KubeOps.Abstractions/Rbac/RbacVerbs.cs, src/KubeOps.Cli/Generators/RbacGenerator.cs, src/KubeOps.Transpiler/Rbac.cs, test/KubeOps.Transpiler.Test/Rbac.Mlc.Test.cs
Adds new `AllExplicit` RBAC verb to state all RBAC verbs explicitly, alternatively to the current `All` RBAC verb that generates a `*` (wildcard) RBAC verb.
As described [here](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources), using wildcards in verb entries could result in overly permissive access being granted. The [principle of least privilege](https://kubernetes.io/docs/concepts/security/rbac-good-practices/#least-privilege) should be employed, using specific verbs to ensure only the permissions required for the workload to function correctly are applied.
=> Add `AllExplicit` RBAC verb & state all default V1Lease RBAC verbs explicitly

src/KubeOps.Operator/Queue/TimedEntityQueue.cs, src/KubeOps.Operator/Watcher/ResourceWatcher{TEntity}.cs
Hi @buehler,
I have a small adjustment here. Two things that are relevant for us:
1) I’ve added the namespace to the logging scope — since we manage multiple namespaces via the CRDs, this gives us better context in the logs and helps us assign log entries more accurately.
2) I made the ResourceWatcher public and the OnEventAsync method protected virtual, so it can be overridden. Given the number of namespaces we manage, we want to allow developers to take over the lead for a single namespace for debugging purposes — but not the entire lead. Therefore, we can’t use the LeaderAwareResourceWatcher as-is; instead, we need a customized ResourceWatcher that checks for leadership on a specific namespace.
I hope these changes align with your design principles.
=> feat: add namespace to logging scope and make ResourceWatcher more extensible

src/KubeOps.Operator/Logging/EntityLoggingScope.cs, src/KubeOps.Operator/Watcher/ResourceWatcher{TEntity}.cs
Hello @buehler,
We’ve noticed that the logging scope isn’t being properly transported to Application Insights. Based on the documentation (https://learn.microsoft.com/en-us/azure/azure-monitor/app/ilogger#logging-scopes), I’ve made a small adjustment so that the scope is passed as key-value pairs into the custom properties of Application Insights. This change should not affect the console output.
> If the scope is of type IReadOnlyCollection<KeyValuePair<string,object>>, then each key/value pair in the collection is added to the Application Insights telemetry as custom properties.
I’ve introduced an EntityLoggingScope that derives from IReadOnlyCollection<KeyValuePair<string, object>>, which is then used accordingly in the BeginScope of the ResourceWatcher:
```csharp
using var _ = …
```
=> feat: introduce `EntityLoggingScope` to support scopes as key-value pairs inside custom properties of application insights

docs/docs/operator/deployment.mdx, docs/docs/operator/logging.mdx, docs/docs/operator/testing/_category_.json
hey @buehler (Christoph),
here’s my first attempt at the documentation — I’m unfortunately not a great writer, so it might take a few rounds until it’s good enough. Feel free to skim through it, and I’d really appreciate any suggestions for improvement.
Setting things up with Docusaurus was really quick and easy — thanks for the tips!
I’ve created a separate page for logging. I didn’t think it quite fit under "Testing," since I see it more as part of the DevOps domain. I hope that works for you.
m. 👋🏼
=> chore: integrated logging documentation

src/KubeOps.Abstractions/Entities/JsonPatchExtensions.cs, src/KubeOps.KubernetesClient/IKubernetesClient.cs, test/KubeOps.Abstractions.Test/Entities/JsonPatchExtensions.Test.cs
Fields like "metadata.uid" and resourceversion
are ever-changing. Those fields should be filtered
during patch to reduce API load.
=> feat(patch): Patch of entity filters volatile metadata fields like UID which are not relevant for Diffs

docs/docs/operator/cli.mdx
Just following along in the docs. It seems like `dotnet kubeops version` does not work in the current version.
```
❯ dotnet kubeops version    
'version' was not matched. Did you mean one of the following?
--version
Required command was not provided.
Unrecognized command or argument 'version'.
```
It seems like  `dotnet kubeops api-version` is the intended command here. 
```
❯ dotnet kubeops api-version
Kubernetes API Version    
┌─────────────┬──────────────┐
│ Git-Version │ v1.31.5+k3s1 │
│ Major       │ 1            │
│ Minor       │ 31           │
│ Platform    │ linux/arm64  │
└─────────────┴──────────────┘
```
Running on MacOs, if it makes a difference.
❯ dotnet kubeops --version
9.11.2+946bf1d8537664fe5dbf068659a809aa94f7ce57
=> docs: `dotnet kubeops version` does not work
